### PR TITLE
Ported GoCommando to netstandard2.0.

### PR DESCRIPTION
**Pull request by madstt**
GoCommando ported to netstandard2.0.

Possible fix for #12.

Side-efffects of this portation is the following:
- Updated GoCommand.Tests to net48.
- Updated Beverage, TestApp and TestApp2 to net48.

### CODE REVIEW

**Comment by mookid8000** [comment]
Hi Mads, I finally got around to check out your PR 😄 

I can't seem to make any of the samples run – I get this error:
```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Configuration.ConfigurationManager, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at GoCommando.Go.InnerRun(ICommandFactory commandFactory, Boolean supportImpersonation)
   at GoCommando.Go.Run(ICommandFactory commandFactory) in C:\temp\GoCommando\GoCommando\Go.cs:line 70
```

Am I doing something wrong?

**Comment by madstt** [comment]
Bummer... i'll get around this ASAP and update the PR...

**Comment by madstt** [comment]
PR updated by adding System.Configuration.ConfigurationManager to Beverage, TestApp, and TestApp2.

I also added CoreTestApp sample project for validating that you can now run netcore apps using GoCommando.

It is actually pretty cool that you can now run you GoCommando application like this: `dotnet run <commandName>`. For the CoreTestApp this means that running `dotnet run new` would print you a new Guid.

**Comment by madstt** [comment]
Has this PR been rejected?

**Comment by mookid8000** [comment]
No, sorry – [it's on the board](https://github.com/orgs/rebus-org/projects/1#card-21077013), but I'm pretty busy these days, so GoCommando is being down-prioritized in favor of more pressing matters.

I'll get to it eventually.

**Comment by mookid8000** [comment]
Hey dude, it was nice of you to update GoCommando to .NET Standard 2.0..... but I've been reluctant to merge this PR, because my own experience with .NET Core was very limited, and I couldn't figure out if appsettings.config had a place in the new world... also, I didn't get the impression that you submitted the PR because it was something you needed right away, so I just waited until I knew some more.

Having played around with .NET Core for a while now, I think I've realized that there might not even be a need for GoCommando (at least in its current form) going forward.

I've made a couple of CLI apps myself using the little [CommandLineParser](https://github.com/commandlineparser/commandline) NuGet package to do most of the heavy lifting. It's been nice enough to work with, so right now I think I prefer to just use that.

For that reason, I'm going to close this PR. 😿 Thanks anyway for submitting it! 🙂

**Pull request closed without merging**
